-- Farm-direct-commerce: producers, offers, news, reviews, cart, orders
-- See openspec/changes/farm-direct-commerce + docs/frontend-gap-analysis-2026-06-10.md

CREATE TABLE producers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL,
    tagline VARCHAR(300),
    photo_url VARCHAR(500),
    style VARCHAR(20) NOT NULL,            -- VALUE | ORGANIC | PREMIUM
    price_level INTEGER NOT NULL,          -- 1..5
    freshness_level INTEGER NOT NULL,      -- 1..5
    rating DECIMAL(3,2) NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    honorary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_producers_honorary ON producers(honorary);
CREATE INDEX idx_producers_style ON producers(style);

CREATE TABLE producer_specialties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    ingredient_name VARCHAR(50) NOT NULL,
    ingredient_id BIGINT,                  -- linked once seed data exists
    CONSTRAINT fk_producer_specialties_producer FOREIGN KEY (producer_id) REFERENCES producers(id)
);
CREATE INDEX idx_producer_specialties_name ON producer_specialties(ingredient_name);

CREATE TABLE producer_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    label VARCHAR(50) NOT NULL,
    CONSTRAINT fk_producer_badges_producer FOREIGN KEY (producer_id) REFERENCES producers(id)
);

CREATE TABLE producer_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    ingredient_id BIGINT,                  -- nullable until seeded
    ingredient_name VARCHAR(50) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    freshness_label VARCHAR(50),
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_producer_offers_producer FOREIGN KEY (producer_id) REFERENCES producers(id)
);
CREATE INDEX idx_producer_offers_ingredient_price ON producer_offers(ingredient_id, price);
CREATE INDEX idx_producer_offers_name_price ON producer_offers(ingredient_name, price);
CREATE INDEX idx_producer_offers_producer ON producer_offers(producer_id);

CREATE TABLE producer_news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    posted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    title VARCHAR(200) NOT NULL,
    image_ref VARCHAR(100),                -- ingredient name or "photo"
    body VARCHAR(2000) NOT NULL,
    CONSTRAINT fk_producer_news_producer FOREIGN KEY (producer_id) REFERENCES producers(id)
);
CREATE INDEX idx_producer_news_producer_posted ON producer_news(producer_id, posted_at DESC);

CREATE TABLE producer_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producer_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,               -- 1..5
    item VARCHAR(50),
    body VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_producer_reviews_producer FOREIGN KEY (producer_id) REFERENCES producers(id)
);
CREATE INDEX idx_producer_reviews_producer ON producer_reviews(producer_id, created_at DESC);
CREATE INDEX idx_producer_reviews_user ON producer_reviews(user_id);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    producer_id BIGINT NOT NULL,
    ingredient_id BIGINT,
    ingredient_name VARCHAR(50) NOT NULL,
    qty INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts(id)
);
CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_number VARCHAR(40) NOT NULL UNIQUE,
    total_amount DECIMAL(12,2) NOT NULL,
    shipping_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
    points_earned DECIMAL(12,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'PAID',   -- PAID | SHIPPING | DELIVERED | CANCELLED
    ordered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_orders_user_ordered ON orders(user_id, ordered_at DESC);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    producer_id BIGINT NOT NULL,
    producer_name VARCHAR(100),
    ingredient_name VARCHAR(50) NOT NULL,
    qty INTEGER NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
CREATE INDEX idx_order_items_order ON order_items(order_id);
