-- AUTO-GENERATED from frontend/components/producers-data.js — 농가 도메인 시드
-- 농가 프로필/특산품/배지/소식/리뷰. producer_offers 단가는 프론트 가격모델 기반(농가별 가격은 공개소스 없음).
-- KAMIS 재료가 적재되면 producer_offers.ingredient_id 링크 + 단가 재산출 가능(후속).

ALTER TABLE producer_reviews ADD COLUMN IF NOT EXISTS author_name VARCHAR(50);

-- (1) 권민성 / 경북영천
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 1,'권민성','경북영천','콩밭 매는 아낙네, 정성으로 키운 잡곡','PREMIUM',5,5,4.9,1280,true WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=1);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 1,'콩' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=1 AND ingredient_name='콩');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 1,'봄동' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=1 AND ingredient_name='봄동');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 1,'시금치' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=1 AND ingredient_name='시금치');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 1,'무' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=1 AND ingredient_name='무');
INSERT INTO producer_badges (producer_id,label) SELECT 1,'산지직송' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=1 AND label='산지직송');
INSERT INTO producer_badges (producer_id,label) SELECT 1,'당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=1 AND label='당일수확');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 1,'콩',10030,'kg','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=1 AND ingredient_name='콩');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 1,'봄동',5310,'봉','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=1 AND ingredient_name='봄동');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 1,'시금치',4480,'단','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=1 AND ingredient_name='시금치');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 1,'무',2600,'개','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=1 AND ingredient_name='무');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 1, TIMESTAMP '2026-05-28 08:58','제철 콩 5월 산지 소식입니다~','콩','경북영천 권민성입니다~ 올해는 일조량이 풍부해 콩 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 콩을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=1 AND title='제철 콩 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 1, TIMESTAMP '2026-04-12 09:00','콩의 계절이 돌아왔습니다~','photo','콩의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 경북영천 콩이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=1 AND title='콩의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 1, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','콩','안녕하세요 생산자 권민성입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=1 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 1,9010,'민지',5,'콩','경북영천에서 바로 받아서 그런지 정말 싱싱해요. 콩 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=1 AND author_name='민지' AND item='콩');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 1,9011,'재현',5,'봄동','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=1 AND author_name='재현' AND item='봄동');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 1,9012,'수안',4,'콩','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=1 AND author_name='수안' AND item='콩');

-- (2) 홍진이 / 경기오산
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 2,'홍진이','경기오산','텃밭에서 갓 딴 유기농 봄동','ORGANIC',4,5,4.8,642,true WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=2);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 2,'봄동' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=2 AND ingredient_name='봄동');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 2,'배추' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=2 AND ingredient_name='배추');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 2,'시금치' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=2 AND ingredient_name='시금치');
INSERT INTO producer_badges (producer_id,label) SELECT 2,'유기농 인증' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=2 AND label='유기농 인증');
INSERT INTO producer_badges (producer_id,label) SELECT 2,'무농약' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=2 AND label='무농약');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 2,'봄동',4900,'봉','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=2 AND ingredient_name='봄동');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 2,'배추',7410,'포기','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=2 AND ingredient_name='배추');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 2,'시금치',4140,'단','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=2 AND ingredient_name='시금치');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 2, TIMESTAMP '2026-05-28 08:58','제철 봄동 5월 산지 소식입니다~','봄동','경기오산 홍진이입니다~ 올해는 일조량이 풍부해 봄동 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 봄동을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=2 AND title='제철 봄동 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 2, TIMESTAMP '2026-04-12 09:00','봄동의 계절이 돌아왔습니다~','photo','봄동의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 경기오산 봄동이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=2 AND title='봄동의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 2, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','봄동','안녕하세요 생산자 홍진이입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=2 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 2,9020,'민지',5,'봄동','경기오산에서 바로 받아서 그런지 정말 싱싱해요. 봄동 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=2 AND author_name='민지' AND item='봄동');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 2,9021,'재현',5,'배추','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=2 AND author_name='재현' AND item='배추');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 2,9022,'수안',4,'봄동','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=2 AND author_name='수안' AND item='봄동');

-- (3) 김상도 / 전남해남
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 3,'김상도','전남해남','겨울 배추 30년 외길, 해남 황토밭','VALUE',2,4,4.7,2104,true WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=3);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 3,'무' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=3 AND ingredient_name='무');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 3,'배추' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=3 AND ingredient_name='배추');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 3,'봄동' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=3 AND ingredient_name='봄동');
INSERT INTO producer_badges (producer_id,label) SELECT 3,'대량 할인' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=3 AND label='대량 할인');
INSERT INTO producer_badges (producer_id,label) SELECT 3,'산지직송' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=3 AND label='산지직송');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 3,'무',2000,'개','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=3 AND ingredient_name='무');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 3,'배추',6190,'포기','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=3 AND ingredient_name='배추');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 3,'봄동',4090,'봉','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=3 AND ingredient_name='봄동');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 3, TIMESTAMP '2026-05-28 08:58','제철 무 5월 산지 소식입니다~','무','전남해남 김상도입니다~ 올해는 일조량이 풍부해 무 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 무을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=3 AND title='제철 무 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 3, TIMESTAMP '2026-04-12 09:00','무의 계절이 돌아왔습니다~','photo','무의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 전남해남 무이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=3 AND title='무의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 3, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','무','안녕하세요 생산자 김상도입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=3 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 3,9030,'민지',5,'무','전남해남에서 바로 받아서 그런지 정말 싱싱해요. 무 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=3 AND author_name='민지' AND item='무');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 3,9031,'재현',5,'배추','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=3 AND author_name='재현' AND item='배추');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 3,9032,'수안',4,'무','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=3 AND author_name='수안' AND item='무');

-- (4) 박정후 / 제주서귀포
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 4,'박정후','제주서귀포','한라산 햇살 머금은 노지 감귤','PREMIUM',5,5,4.9,980,true WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=4);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 4,'감귤' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=4 AND ingredient_name='감귤');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 4,'귤' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=4 AND ingredient_name='귤');
INSERT INTO producer_badges (producer_id,label) SELECT 4,'프리미엄' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=4 AND label='프리미엄');
INSERT INTO producer_badges (producer_id,label) SELECT 4,'당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=4 AND label='당일수확');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 4,'감귤',11680,'kg','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=4 AND ingredient_name='감귤');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 4,'귤',11680,'kg','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=4 AND ingredient_name='귤');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 4, TIMESTAMP '2026-05-28 08:58','제철 감귤 5월 산지 소식입니다~','감귤','제주서귀포 박정후입니다~ 올해는 일조량이 풍부해 감귤 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 감귤을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=4 AND title='제철 감귤 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 4, TIMESTAMP '2026-04-12 09:00','감귤의 계절이 돌아왔습니다~','photo','감귤의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 제주서귀포 감귤이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=4 AND title='감귤의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 4, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','감귤','안녕하세요 생산자 박정후입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=4 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 4,9040,'민지',5,'감귤','제주서귀포에서 바로 받아서 그런지 정말 싱싱해요. 감귤 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=4 AND author_name='민지' AND item='감귤');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 4,9041,'재현',5,'귤','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=4 AND author_name='재현' AND item='귤');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 4,9042,'수안',4,'감귤','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=4 AND author_name='수안' AND item='감귤');

-- (5) 이수향 / 강원평창
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 5,'이수향','강원평창','고랭지 700m 무농약 채소','ORGANIC',4,5,4.8,415,true WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=5);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 5,'시금치' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=5 AND ingredient_name='시금치');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 5,'무' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=5 AND ingredient_name='무');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 5,'브로콜리' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=5 AND ingredient_name='브로콜리');
INSERT INTO producer_badges (producer_id,label) SELECT 5,'유기농 인증' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=5 AND label='유기농 인증');
INSERT INTO producer_badges (producer_id,label) SELECT 5,'고랭지' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=5 AND label='고랭지');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 5,'시금치',4140,'단','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=5 AND ingredient_name='시금치');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 5,'무',2400,'개','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=5 AND ingredient_name='무');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 5,'브로콜리',3260,'개','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=5 AND ingredient_name='브로콜리');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 5, TIMESTAMP '2026-05-28 08:58','제철 시금치 5월 산지 소식입니다~','시금치','강원평창 이수향입니다~ 올해는 일조량이 풍부해 시금치 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 시금치을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=5 AND title='제철 시금치 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 5, TIMESTAMP '2026-04-12 09:00','시금치의 계절이 돌아왔습니다~','photo','시금치의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 강원평창 시금치이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=5 AND title='시금치의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 5, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','시금치','안녕하세요 생산자 이수향입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=5 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 5,9050,'민지',5,'시금치','강원평창에서 바로 받아서 그런지 정말 싱싱해요. 시금치 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=5 AND author_name='민지' AND item='시금치');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 5,9051,'재현',5,'무','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=5 AND author_name='재현' AND item='무');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 5,9052,'수안',4,'시금치','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=5 AND author_name='수안' AND item='시금치');

-- (6) 정대근 / 충남논산
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 6,'정대근','충남논산','딸기보다 단 대파, 논산 들녘','VALUE',2,4,4.6,738,false WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=6);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 6,'대파' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=6 AND ingredient_name='대파');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 6,'마늘' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=6 AND ingredient_name='마늘');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 6,'무' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=6 AND ingredient_name='무');
INSERT INTO producer_badges (producer_id,label) SELECT 6,'가성비' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=6 AND label='가성비');
INSERT INTO producer_badges (producer_id,label) SELECT 6,'산지직송' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=6 AND label='산지직송');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 6,'대파',3180,'단','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=6 AND ingredient_name='대파');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 6,'마늘',8100,'접','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=6 AND ingredient_name='마늘');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 6,'무',2000,'개','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=6 AND ingredient_name='무');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 6, TIMESTAMP '2026-05-28 08:58','제철 대파 5월 산지 소식입니다~','대파','충남논산 정대근입니다~ 올해는 일조량이 풍부해 대파 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 대파을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=6 AND title='제철 대파 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 6, TIMESTAMP '2026-04-12 09:00','대파의 계절이 돌아왔습니다~','photo','대파의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 충남논산 대파이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=6 AND title='대파의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 6, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','대파','안녕하세요 생산자 정대근입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=6 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 6,9060,'민지',5,'대파','충남논산에서 바로 받아서 그런지 정말 싱싱해요. 대파 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=6 AND author_name='민지' AND item='대파');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 6,9061,'재현',5,'마늘','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=6 AND author_name='재현' AND item='마늘');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 6,9062,'수안',4,'대파','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=6 AND author_name='수안' AND item='대파');

-- (7) 최영자 / 경남통영
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 7,'최영자','경남통영','통영 바다를 품은 새벽 생굴','PREMIUM',5,5,4.9,1560,false WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=7);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 7,'굴' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=7 AND ingredient_name='굴');
INSERT INTO producer_badges (producer_id,label) SELECT 7,'새벽 출고' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=7 AND label='새벽 출고');
INSERT INTO producer_badges (producer_id,label) SELECT 7,'콜드체인' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=7 AND label='콜드체인');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 7,'굴',15220,'kg','당일수확' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=7 AND ingredient_name='굴');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 7, TIMESTAMP '2026-05-28 08:58','제철 굴 5월 산지 소식입니다~','굴','경남통영 최영자입니다~ 올해는 일조량이 풍부해 굴 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 굴을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=7 AND title='제철 굴 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 7, TIMESTAMP '2026-04-12 09:00','굴의 계절이 돌아왔습니다~','photo','굴의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 경남통영 굴이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=7 AND title='굴의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 7, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','굴','안녕하세요 생산자 최영자입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=7 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 7,9070,'민지',5,'굴','경남통영에서 바로 받아서 그런지 정말 싱싱해요. 굴 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=7 AND author_name='민지' AND item='굴');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 7,9071,'재현',5,'굴','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=7 AND author_name='재현' AND item='굴');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 7,9072,'수안',4,'굴','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=7 AND author_name='수안' AND item='굴');

-- (8) 윤도현 / 경북상주
INSERT INTO producers (id,name,region,tagline,style,price_level,freshness_level,rating,review_count,honorary) SELECT 8,'윤도현','경북상주','유기농 단호박·고구마 농장','ORGANIC',3,4,4.7,521,false WHERE NOT EXISTS (SELECT 1 FROM producers WHERE id=8);
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 8,'단호박' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=8 AND ingredient_name='단호박');
INSERT INTO producer_specialties (producer_id,ingredient_name) SELECT 8,'고구마' WHERE NOT EXISTS (SELECT 1 FROM producer_specialties WHERE producer_id=8 AND ingredient_name='고구마');
INSERT INTO producer_badges (producer_id,label) SELECT 8,'유기농 인증' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=8 AND label='유기농 인증');
INSERT INTO producer_badges (producer_id,label) SELECT 8,'산지직송' WHERE NOT EXISTS (SELECT 1 FROM producer_badges WHERE producer_id=8 AND label='산지직송');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 8,'단호박',4200,'개','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=8 AND ingredient_name='단호박');
INSERT INTO producer_offers (producer_id,ingredient_name,price,unit,freshness_label) SELECT 8,'고구마',7150,'kg','수확 1일 이내' WHERE NOT EXISTS (SELECT 1 FROM producer_offers WHERE producer_id=8 AND ingredient_name='고구마');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 8, TIMESTAMP '2026-05-28 08:58','제철 단호박 5월 산지 소식입니다~','단호박','경북상주 윤도현입니다~ 올해는 일조량이 풍부해 단호박 품질이 예년보다 좋습니다. 경매장 시세는 올랐지만, 소비자분들께 신선하고 맛있는 단호박을(를) 보내드린다는 자부심으로 합리적인 가격에 정직하게 판매하고 있습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=8 AND title='제철 단호박 5월 산지 소식입니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 8, TIMESTAMP '2026-04-12 09:00','단호박의 계절이 돌아왔습니다~','photo','단호박의 계절이 다가왔습니다. 이번 해는 일조량이 풍부하여 경북상주 단호박이(가) 무럭무럭 잘 자라고 있습니다. 작년 대비 생산량과 품질이 더 좋아졌습니다~ 산지의 신선함 그대로 정직하게 판매하겠습니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=8 AND title='단호박의 계절이 돌아왔습니다~');
INSERT INTO producer_news (producer_id,posted_at,title,image_ref,body) SELECT 8, TIMESTAMP '2026-03-07 08:56','봄을 알리는 첫 수확을 시작하였습니다~','단호박','안녕하세요 생산자 윤도현입니다~ 겨울 날씨가 포근하고 일조량이 좋아 수확을 조금 빨리 시작했습니다. 올해 생산량과 품질, 당도 모두 우수할 것으로 보입니다.' WHERE NOT EXISTS (SELECT 1 FROM producer_news WHERE producer_id=8 AND title='봄을 알리는 첫 수확을 시작하였습니다~');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 8,9080,'민지',5,'단호박','경북상주에서 바로 받아서 그런지 정말 싱싱해요. 단호박 이렇게 신선한 건 처음이에요. 재구매 의사 100%입니다!', TIMESTAMP '2026-05-30 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=8 AND author_name='민지' AND item='단호박');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 8,9081,'재현',5,'고구마','포장도 꼼꼼하고 당일 수확이라 그런지 식감이 살아있어요. 가족들이 다 좋아하네요.', TIMESTAMP '2026-05-21 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=8 AND author_name='재현' AND item='고구마');
INSERT INTO producer_reviews (producer_id,user_id,author_name,rating,item,body,created_at) SELECT 8,9082,'수안',4,'단호박','맛은 아주 좋은데 배송이 하루 늦었어요. 그래도 품질 보고 또 주문할 것 같습니다.', TIMESTAMP '2026-05-12 10:00' WHERE NOT EXISTS (SELECT 1 FROM producer_reviews WHERE producer_id=8 AND author_name='수안' AND item='단호박');

-- 고정 ID(1~8) 명시 삽입 후 identity 시퀀스 보정 (이후 기본값 생성 시 충돌 방지)
ALTER TABLE producers ALTER COLUMN id RESTART WITH 9;
