CREATE TABLE IF NOT EXISTS schema_version_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_version_note (note)
SELECT 'phase-0 baseline'
WHERE NOT EXISTS (
    SELECT 1 FROM schema_version_note WHERE note = 'phase-0 baseline'
);
