-- Offer → 상품(Product) 확장: producer_offers에 상품 속성 추가 + 사진/태그 정규화 테이블.
-- 프론트 화면 16 상품리스트 / 17 상품상세 / 25 판매등록 근거.
-- See openspec/changes/offer-product-expansion.
-- 모든 신규 필드는 nullable — 기존 offer/시드 데이터 호환.

ALTER TABLE producer_offers ADD COLUMN title VARCHAR(150);
ALTER TABLE producer_offers ADD COLUMN description VARCHAR(1000);
ALTER TABLE producer_offers ADD COLUMN category VARCHAR(30);

-- 상품 사진 (다중, 대표 1장 지정)
CREATE TABLE offer_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_offer_photos_offer FOREIGN KEY (offer_id) REFERENCES producer_offers(id)
);
CREATE INDEX idx_offer_photos_offer ON offer_photos(offer_id, sort_order);

-- 상품 태그 (산지직송 · 무료배송 · 콜드체인 등, 자유 텍스트 자기신고)
CREATE TABLE offer_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    label VARCHAR(40) NOT NULL,
    CONSTRAINT fk_offer_tags_offer FOREIGN KEY (offer_id) REFERENCES producer_offers(id)
);
CREATE INDEX idx_offer_tags_offer ON offer_tags(offer_id);
