-- 상품 옵션(규격/variant): 한 상품(offer) 안의 여러 규격(한 단/한 되/3kg 등) + 각 가격.
-- label을 강제 열거하지 않고 수량+단위(자유, 추천목록 UX)+가격으로 반-구조화. See openspec/changes/offer-options.
CREATE TABLE offer_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    quantity DECIMAL(12,2),
    unit VARCHAR(30),
    price DECIMAL(12,2) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_offer_options_offer FOREIGN KEY (offer_id) REFERENCES producer_offers(id)
);
CREATE INDEX idx_offer_options_offer ON offer_options(offer_id, sort_order);
