-- 판매등록 화면(24 ScreenFarmUpload) 2026-06-12 필드 추가 근거.
-- ① 인증마크(다중, 필수≥1) ② 재고 수량 ③ 보관방법(+설명).
-- 신규 컬럼은 nullable — 기존 offer/시드 데이터 호환.

-- 재고 수량 (실시간 판매 가능 수량). null = 미설정.
ALTER TABLE producer_offers ADD COLUMN stock_quantity INTEGER;

-- 보관방법 (냉장/냉동/실온/그늘 등) + 구매자 안내 설명
ALTER TABLE producer_offers ADD COLUMN storage_method VARCHAR(30);
ALTER TABLE producer_offers ADD COLUMN storage_note VARCHAR(500);

-- 인증마크 (무농약 · 유기농 · GAP · 친환경 · 지리적표시 등, 다중)
CREATE TABLE offer_certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    label VARCHAR(40) NOT NULL,
    CONSTRAINT fk_offer_certifications_offer FOREIGN KEY (offer_id) REFERENCES producer_offers(id)
);
CREATE INDEX idx_offer_certifications_offer ON offer_certifications(offer_id);
