-- 배송지(사용자 주소록). BACKEND-REQUIREMENTS #4.
-- 기본 배송지는 사용자당 하나만 true(애플리케이션에서 보장).
CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipient_name VARCHAR(50) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    zip_code VARCHAR(10),
    address1 VARCHAR(200) NOT NULL,
    address2 VARCHAR(200),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_user_addresses_user ON user_addresses(user_id, is_default);
