-- 상품 상세정보 섹션(접기/펼치기): 한 상품(offer)에 제목+본문 섹션 여러 개. BACKEND-REQUIREMENTS #10.
-- 없으면 프론트가 description 단일 섹션으로 폴백하므로, 데이터 없으면 GET /products/{id}는 detailSections=[].
-- (V31은 기존 seed 마이그레이션과 충돌하여 V34로 이동함)
CREATE TABLE offer_detail_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    image_url VARCHAR(500),                 -- 섹션별 상세 이미지(nullable). 없으면 프론트가 텍스트만 렌더
    heading VARCHAR(120) NOT NULL,
    body VARCHAR(4000) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_offer_detail_sections_offer FOREIGN KEY (offer_id) REFERENCES producer_offers(id)
);
CREATE INDEX idx_offer_detail_sections_offer ON offer_detail_sections(offer_id, sort_order);
