CREATE TABLE price_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    source VARCHAR(50) NOT NULL,
    price_type VARCHAR(50) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    observed_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_snapshots_ingredient_id
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (id)
);

CREATE INDEX idx_price_snapshots_ingredient_observed_date
    ON price_snapshots (ingredient_id, observed_date);

CREATE INDEX idx_price_snapshots_source_observed_date
    ON price_snapshots (source, observed_date);

CREATE TABLE price_forecasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    min_price NUMERIC(12,2) NOT NULL,
    max_price NUMERIC(12,2) NOT NULL,
    forecast_date DATE NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_forecasts_ingredient_id
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (id)
);
