-- V41: 식재료 대체재 시드 (재료_상세정보_최종.json, 98쌍)
-- 대체재명도 우리 식재료(69종) 안에 있어 substitute_ingredient_id 를 이름으로 해석.
-- 양쪽 ingredient 존재 + (ingredient_id, substitute_ingredient_id) 미존재 가드로 멱등.

-- 쌀
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='쌀' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='찹쌀' AND active=true LIMIT 1), 75, '밥·떡의 주재료로 찰기 정도만 다르게 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='쌀' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='찹쌀' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='쌀' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='찹쌀' AND active=true LIMIT 1));

-- 찹쌀
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='찹쌀' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='쌀' AND active=true LIMIT 1), 75, '밥·떡의 주재료로 찰기 정도만 다르게 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='찹쌀' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='쌀' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='찹쌀' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='쌀' AND active=true LIMIT 1));

-- 팥
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='팥' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='녹두' AND active=true LIMIT 1), 60, '두류로 죽·앙금·빈대떡에 쓰며 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='팥' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='녹두' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='팥' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='녹두' AND active=true LIMIT 1));

-- 녹두
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='녹두' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='팥' AND active=true LIMIT 1), 60, '두류로 죽·앙금·빈대떡에 쓰며 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='녹두' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='팥' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='녹두' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='팥' AND active=true LIMIT 1));

-- 고구마
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='고구마' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='감자' AND active=true LIMIT 1), 70, '구황작물로 찌거나 구워 먹고 조림·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='고구마' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='감자' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='고구마' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='감자' AND active=true LIMIT 1));

-- 감자
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='감자' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='고구마' AND active=true LIMIT 1), 70, '구황작물로 찌거나 구워 먹고 조림·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='감자' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='고구마' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='감자' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='고구마' AND active=true LIMIT 1));

-- 배추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1));

-- 양배추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='브로콜리' AND active=true LIMIT 1), 45, '십자화과 채소로 데치거나 볶아 곁들임에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='브로콜리' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='브로콜리' AND active=true LIMIT 1));

-- 시금치
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='시금치' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='유채' AND active=true LIMIT 1), 60, '데쳐 무치는 잎나물로 무침·국에 활용해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='시금치' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='유채' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='시금치' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='유채' AND active=true LIMIT 1));

-- 상추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양상추' AND active=true LIMIT 1), 75, '잎상추류로 쌈·샐러드에 서로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='상추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양상추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양상추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='깻잎' AND active=true LIMIT 1), 60, '쌈채소로 고기·밥을 싸 먹는 데 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='상추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='깻잎' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='깻잎' AND active=true LIMIT 1));

-- 얼갈이배추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1));

-- 수박
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='수박' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='참외' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='수박' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='멜론' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1));

-- 참외
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='참외' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='수박' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='참외' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='멜론' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1));

-- 호박
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='호박' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='가지' AND active=true LIMIT 1), 45, '볶음·구이에 부드러운 식감을 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='호박' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='가지' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='호박' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='가지' AND active=true LIMIT 1));

-- 토마토
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='토마토' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='방울토마토' AND active=true LIMIT 1), 90, '같은 토마토라 생식·샐러드·소스에 그대로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='토마토' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='방울토마토' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='토마토' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='방울토마토' AND active=true LIMIT 1));

-- 무
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='열무' AND active=true LIMIT 1), 65, '같은 무 계열로 김치·국에 활용해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='무' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='열무' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='열무' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='당근' AND active=true LIMIT 1), 50, '뿌리채소로 조림·국에 식감을 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='무' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='당근' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='당근' AND active=true LIMIT 1));

-- 당근
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='당근' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1), 50, '뿌리채소로 조림·국에 식감을 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='당근' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='무' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='당근' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1));

-- 열무
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='열무' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1), 65, '같은 무 계열로 김치·국에 활용해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='열무' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='무' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='열무' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='무' AND active=true LIMIT 1));

-- 건고추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='건고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='붉은고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='건고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='고춧가루' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1));

-- 풋고추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='풋고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='꽈리고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='풋고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='오이고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1));

-- 붉은고추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='붉은고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='건고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='붉은고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='고춧가루' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1));

-- 양파
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양파' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1), 55, '향을 내는 양념 채소로 볶음·국 베이스에 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양파' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='깐마늘(국산)' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양파' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1));

-- 파
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='파' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1), 45, '향 채소로 전·무침·고명에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='파' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='부추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='파' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1));

-- 생강
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='생강' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1), 40, '양념 향신채로 잡내 잡기에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='생강' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='깐마늘(국산)' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='생강' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1));

-- 고춧가루
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='고춧가루' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='건고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='건고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1), 70, '고추 양념류로 매운맛과 색을 내는 데 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='고춧가루' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='붉은고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='고춧가루' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='붉은고추' AND active=true LIMIT 1));

-- 미나리
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='미나리' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1), 55, '향이 있는 줄기·잎 채소로 무침·전·국에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='미나리' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='부추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='미나리' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1));

-- 깻잎
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='깻잎' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1), 60, '쌈채소로 고기·밥을 싸 먹는 데 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='깻잎' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='상추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='깻잎' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1));

-- 피망
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='피망' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='파프리카' AND active=true LIMIT 1), 90, '단고추류로 색감과 아삭한 식감이 비슷해 볶음·생채에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='피망' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='파프리카' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='피망' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='파프리카' AND active=true LIMIT 1));

-- 파프리카
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='파프리카' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='피망' AND active=true LIMIT 1), 90, '단고추류로 색감과 아삭한 식감이 비슷해 볶음·생채에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='파프리카' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='피망' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='파프리카' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='피망' AND active=true LIMIT 1));

-- 멜론
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='멜론' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='수박' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='수박' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1), 75, '여름 박과 과일로 수분이 많고 달아 생과·화채에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='멜론' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='참외' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='멜론' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='참외' AND active=true LIMIT 1));

-- 깐마늘(국산)
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양파' AND active=true LIMIT 1), 55, '향을 내는 양념 채소로 볶음·국 베이스에 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='깐마늘(국산)' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양파' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양파' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='생강' AND active=true LIMIT 1), 40, '양념 향신채로 잡내 잡기에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='깐마늘(국산)' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='생강' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='깐마늘(국산)' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='생강' AND active=true LIMIT 1));

-- 알배기배추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='얼갈이배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='얼갈이배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), 85, '같은 잎배추·양배추류로 식감과 쓰임새(국·김치·쌈·볶음)가 비슷해 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='봄동' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='청경채' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1));

-- 브로콜리
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='브로콜리' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1), 45, '십자화과 채소로 데치거나 볶아 곁들임에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='브로콜리' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='양배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='브로콜리' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='양배추' AND active=true LIMIT 1));

-- 방울토마토
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='방울토마토' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='토마토' AND active=true LIMIT 1), 90, '같은 토마토라 생식·샐러드·소스에 그대로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='방울토마토' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='토마토' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='방울토마토' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='토마토' AND active=true LIMIT 1));

-- 참깨
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='들깨' AND active=true LIMIT 1), 50, '고소한 씨앗·가루로 나물·고명에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='참깨' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='들깨' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='들깨' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), 40, '고소한 씨앗·견과로 고명·가루로 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='참깨' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1));

-- 땅콩
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='호두' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='아몬드' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1), 40, '고소한 씨앗·견과로 고명·가루로 일부 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='참깨' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1));

-- 느타리버섯
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1));

-- 팽이버섯
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1));

-- 새송이버섯
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1));

-- 호두
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='호두' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='아몬드' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='호두' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1));

-- 아몬드
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='아몬드' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='호두' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='호두' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1), 75, '고소한 견과류로 간식·고명·샐러드에 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='아몬드' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='땅콩' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='아몬드' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='땅콩' AND active=true LIMIT 1));

-- 사과
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='사과' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='배' AND active=true LIMIT 1), 80, '아삭하고 달아 생과·샐러드·갈아쓰기에 서로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='사과' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='배' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='사과' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='배' AND active=true LIMIT 1));

-- 배
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='배' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='사과' AND active=true LIMIT 1), 80, '아삭하고 달아 생과·샐러드·갈아쓰기에 서로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='배' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='사과' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='배' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='사과' AND active=true LIMIT 1));

-- 파인애플
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='파인애플' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='망고' AND active=true LIMIT 1), 60, '달콤한 열대과일로 생과·디저트에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='파인애플' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='망고' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='파인애플' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='망고' AND active=true LIMIT 1));

-- 오렌지
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='오렌지' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='레몬' AND active=true LIMIT 1), 50, '감귤류로 즙·향을 내는 데 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='오렌지' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='레몬' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='오렌지' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='레몬' AND active=true LIMIT 1));

-- 레몬
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='레몬' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='오렌지' AND active=true LIMIT 1), 50, '감귤류로 즙·향을 내는 데 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='레몬' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='오렌지' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='레몬' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='오렌지' AND active=true LIMIT 1));

-- 망고
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='망고' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='파인애플' AND active=true LIMIT 1), 60, '달콤한 열대과일로 생과·디저트에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='망고' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='파인애플' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='망고' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='파인애플' AND active=true LIMIT 1));

-- 부추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='미나리' AND active=true LIMIT 1), 55, '향이 있는 줄기·잎 채소로 무침·전·국에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='부추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='미나리' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='미나리' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='파' AND active=true LIMIT 1), 45, '향 채소로 전·무침·고명에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='부추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='파' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='부추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='파' AND active=true LIMIT 1));

-- 가지
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='가지' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='호박' AND active=true LIMIT 1), 45, '볶음·구이에 부드러운 식감을 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='가지' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='호박' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='가지' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='호박' AND active=true LIMIT 1));

-- 꽈리고추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='꽈리고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='풋고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='꽈리고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='오이고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1));

-- 냉이
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='냉이' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='달래' AND active=true LIMIT 1), 70, '봄나물로 향긋해 무침·된장국에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='냉이' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='달래' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='냉이' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='달래' AND active=true LIMIT 1));

-- 청경채
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='청경채' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='봄동' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='청경채' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1));

-- 봄동
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='봄동' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='청경채' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='청경채' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1), 75, '작은 잎배추류로 겉절이·국·볶음에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='봄동' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='알배기배추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='봄동' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='알배기배추' AND active=true LIMIT 1));

-- 달래
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='달래' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='냉이' AND active=true LIMIT 1), 70, '봄나물로 향긋해 무침·된장국에 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='달래' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='냉이' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='달래' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='냉이' AND active=true LIMIT 1));

-- 들깨
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='들깨' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1), 50, '고소한 씨앗·가루로 나물·고명에 일부 대체해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='들깨' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='참깨' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='들깨' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='참깨' AND active=true LIMIT 1));

-- 오이고추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='오이고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='풋고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='풋고추' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1), 70, '순한 풋고추류로 볶음·조림·반찬에 서로 대체할 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='오이고추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='꽈리고추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='오이고추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='꽈리고추' AND active=true LIMIT 1));

-- 유채
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='유채' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='시금치' AND active=true LIMIT 1), 60, '데쳐 무치는 잎나물로 무침·국에 활용해요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='유채' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='시금치' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='유채' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='시금치' AND active=true LIMIT 1));

-- 양상추
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='양상추' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1), 75, '잎상추류로 쌈·샐러드에 서로 대체돼요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='양상추' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='상추' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='양상추' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='상추' AND active=true LIMIT 1));

-- 표고버섯
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='느타리버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='느타리버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='팽이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='팽이버섯' AND active=true LIMIT 1));
INSERT INTO ingredient_substitutes (ingredient_id, substitute_ingredient_id, score, reason) SELECT (SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1), (SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1), 80, '같은 버섯류로 볶음·국·전골에 향과 식감을 비슷하게 낼 수 있어요' WHERE EXISTS (SELECT 1 FROM ingredients WHERE name='표고버섯' AND active=true) AND EXISTS (SELECT 1 FROM ingredients WHERE name='새송이버섯' AND active=true) AND NOT EXISTS (SELECT 1 FROM ingredient_substitutes x WHERE x.ingredient_id=(SELECT id FROM ingredients WHERE name='표고버섯' AND active=true LIMIT 1) AND x.substitute_ingredient_id=(SELECT id FROM ingredients WHERE name='새송이버섯' AND active=true LIMIT 1));

