CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    image_url VARCHAR(500),
    difficulty VARCHAR(50) NOT NULL,
    minutes INTEGER NOT NULL,
    servings INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recipes_title ON recipes (title);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity NUMERIC(12, 2),
    unit VARCHAR(30),
    optional BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_ingredients_recipe_id
        FOREIGN KEY (recipe_id)
        REFERENCES recipes (id),
    CONSTRAINT fk_recipe_ingredients_ingredient_id
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (id)
);

CREATE INDEX idx_recipe_ingredients_ingredient_id
    ON recipe_ingredients (ingredient_id);

CREATE TABLE recipe_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    step_number INTEGER NOT NULL,
    description TEXT NOT NULL,
    minutes INTEGER,
    image_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_steps_recipe_id
        FOREIGN KEY (recipe_id)
        REFERENCES recipes (id),
    CONSTRAINT uk_recipe_steps_recipe_id_step_number
        UNIQUE (recipe_id, step_number)
);

CREATE TABLE ingredient_substitutes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    substitute_ingredient_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ingredient_substitutes_ingredient_id
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients (id),
    CONSTRAINT fk_ingredient_substitutes_substitute_ingredient_id
        FOREIGN KEY (substitute_ingredient_id)
        REFERENCES ingredients (id)
);
