-- V52: 레시피 태그 테이블 + 시드.
-- recipes 에는 별도 태그 데이터가 없으므로, 연결된 활성 식재료 이름을 태그로 파생한다
-- (제철 식재료 앱 특성상 "재료" 필터가 가장 유용). 멱등(ON CONFLICT DO NOTHING).

CREATE TABLE IF NOT EXISTS recipe_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_tags_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    CONSTRAINT uk_recipe_tags_recipe_tag UNIQUE (recipe_id, tag)
);

CREATE INDEX IF NOT EXISTS idx_recipe_tags_tag ON recipe_tags (tag);
CREATE INDEX IF NOT EXISTS idx_recipe_tags_recipe ON recipe_tags (recipe_id);

-- 시드: recipe_ingredients 에 연결된 활성 식재료 이름을 태그로.
-- 멱등 — 기존 코드베이스 관례(WHERE NOT EXISTS)를 따른다(H2 PostgreSQL 모드 호환).
INSERT INTO recipe_tags (recipe_id, tag)
SELECT DISTINCT ri.recipe_id, ing.name
FROM recipe_ingredients ri
JOIN ingredients ing ON ing.id = ri.ingredient_id
WHERE ing.active = TRUE
  AND NOT EXISTS (
    SELECT 1 FROM recipe_tags rt
    WHERE rt.recipe_id = ri.recipe_id AND rt.tag = ing.name
  );
