-- V55: 제철 큐레이션 테이블 (curations + 관련 식재료/레시피 조인 테이블)
-- 홈 히어로 = curations 의 메인 이미지/타이틀/서브타이틀, 카드 탭 → 큐레이션 상세(/curation/{id}).
-- 상세 페이지: 메인 이미지 · 메인 타이틀 · 서브타이틀 · 제철 이야기 + 관련 식재료/레시피 탭.

CREATE TABLE curations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    main_image_url VARCHAR(500),
    main_title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(300),
    seasonal_story TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_curations_active_order ON curations (active, display_order, id);

CREATE TABLE curation_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curation_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_curation_ingredients_curation
        FOREIGN KEY (curation_id) REFERENCES curations (id) ON DELETE CASCADE,
    CONSTRAINT fk_curation_ingredients_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) ON DELETE CASCADE,
    CONSTRAINT uk_curation_ingredients UNIQUE (curation_id, ingredient_id)
);

CREATE INDEX idx_curation_ingredients_curation ON curation_ingredients (curation_id);

CREATE TABLE curation_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curation_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_curation_recipes_curation
        FOREIGN KEY (curation_id) REFERENCES curations (id) ON DELETE CASCADE,
    CONSTRAINT fk_curation_recipes_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE,
    CONSTRAINT uk_curation_recipes UNIQUE (curation_id, recipe_id)
);

CREATE INDEX idx_curation_recipes_curation ON curation_recipes (curation_id);
