CREATE TABLE recommendation_sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, status VARCHAR(50) NOT NULL,
 request_json TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_recommendation_sessions_user FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE recommendation_messages (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, session_id BIGINT NOT NULL, role VARCHAR(50) NOT NULL,
 content TEXT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_recommendation_messages_session FOREIGN KEY(session_id) REFERENCES recommendation_sessions(id)
);
CREATE TABLE shopping_plans (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, session_id BIGINT NOT NULL,
 days INTEGER NOT NULL, people INTEGER NOT NULL, budget NUMERIC(12,2), estimated_total NUMERIC(12,2) NOT NULL DEFAULT 0,
 status VARCHAR(50) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_shopping_plans_user FOREIGN KEY(user_id) REFERENCES users(id),
 CONSTRAINT fk_shopping_plans_session FOREIGN KEY(session_id) REFERENCES recommendation_sessions(id)
);
CREATE TABLE shopping_plan_meals (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, plan_id BIGINT NOT NULL, recipe_id BIGINT NOT NULL,
 meal_date DATE NOT NULL, meal_type VARCHAR(50) NOT NULL,
 CONSTRAINT fk_shopping_plan_meals_plan FOREIGN KEY(plan_id) REFERENCES shopping_plans(id),
 CONSTRAINT fk_shopping_plan_meals_recipe FOREIGN KEY(recipe_id) REFERENCES recipes(id)
);
CREATE TABLE shopping_plan_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, plan_id BIGINT NOT NULL, ingredient_id BIGINT NOT NULL,
 quantity NUMERIC(12,2), unit VARCHAR(30), estimated_price NUMERIC(12,2), selected BOOLEAN NOT NULL DEFAULT TRUE,
 CONSTRAINT fk_shopping_plan_items_plan FOREIGN KEY(plan_id) REFERENCES shopping_plans(id),
 CONSTRAINT fk_shopping_plan_items_ingredient FOREIGN KEY(ingredient_id) REFERENCES ingredients(id)
);
