CREATE TABLE creators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    display_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_creators_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE reels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT,
    creator_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    video_url VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500) NOT NULL,
    ingredient_tags VARCHAR(500),
    duration_seconds INTEGER,
    status VARCHAR(50) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reels_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id),
    CONSTRAINT fk_reels_creator FOREIGN KEY (creator_id) REFERENCES creators(id)
);

CREATE INDEX idx_reels_status_published_at ON reels(status, published_at DESC);

CREATE TABLE reel_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reel_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reel_reactions_reel FOREIGN KEY (reel_id) REFERENCES reels(id),
    CONSTRAINT fk_reel_reactions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_reel_reactions_user_type UNIQUE (reel_id, user_id, reaction_type)
);

CREATE TABLE reel_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reel_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(1000) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reel_comments_reel FOREIGN KEY (reel_id) REFERENCES reels(id),
    CONSTRAINT fk_reel_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_reel_comments_reel_id_id ON reel_comments(reel_id, id);
