CREATE TABLE ingredient_nutritions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL UNIQUE,
    calories INTEGER,
    carbohydrate DECIMAL(12,2),
    sugar DECIMAL(12,2),
    fiber DECIMAL(12,2),
    protein DECIMAL(12,2),
    fat DECIMAL(12,2),
    vitamin_c VARCHAR(50),
    potassium VARCHAR(50),
    folate VARCHAR(50),
    CONSTRAINT fk_ingredient_nutritions_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE ingredient_care_tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    tip_order INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    CONSTRAINT fk_ingredient_care_tips_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE INDEX idx_ingredient_care_tips_ingredient_order ON ingredient_care_tips(ingredient_id, tip_order);

CREATE TABLE ingredient_storage_tips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    storage_type VARCHAR(50) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    icon VARCHAR(50),
    CONSTRAINT fk_ingredient_storage_tips_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE INDEX idx_ingredient_storage_tips_ingredient ON ingredient_storage_tips(ingredient_id);

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    store_type VARCHAR(50) NOT NULL,
    logo_url VARCHAR(500),
    logo_text VARCHAR(20),
    brand_color VARCHAR(30),
    external_url VARCHAR(500),
    region_code VARCHAR(50)
);

CREATE TABLE store_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    price_range_min DECIMAL(12,2),
    price_range_max DECIMAL(12,2),
    original_price DECIMAL(12,2),
    discount_rate INTEGER,
    unit VARCHAR(30) NOT NULL,
    delivery_label VARCHAR(100),
    badge VARCHAR(50),
    product_url VARCHAR(500),
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_offers_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_store_offers_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE INDEX idx_store_offers_ingredient_price ON store_offers(ingredient_id, price);
