package com.seasonaldining.search.controller;
import com.seasonaldining.ingredient.entity.Ingredient; import com.seasonaldining.ingredient.repository.IngredientRepository; import com.seasonaldining.recipe.entity.Recipe; import com.seasonaldining.recipe.repository.*; import com.seasonaldining.support.UserDataCleaner; import com.seasonaldining.user.entity.User; import com.seasonaldining.user.repository.UserRepository; import com.seasonaldining.common.security.JwtTokenProvider;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class SearchControllerTest {
 @Autowired MockMvc mvc; @Autowired IngredientRepository ingredients; @Autowired RecipeRepository recipes; @Autowired RecipeStepRepository steps; @Autowired RecipeIngredientRepository recipeIngredients; @Autowired JdbcTemplate jdbc; @Autowired UserRepository users; @Autowired JwtTokenProvider jwt;
 // search_keywords 는 전역(비 사용자 스코프) 테이블 + V49 시드가 채워둔다 → trending 단언을 위해 매 테스트 초기화.
 @BeforeEach void setUp(){UserDataCleaner.clean(jdbc);jdbc.update("DELETE FROM search_keywords");steps.deleteAll();recipeIngredients.deleteAll();recipes.deleteAll();ingredients.deleteAll();}
 @Test void searchesIngredientsAndRecipes() throws Exception{ingredients.save(new Ingredient("무","채소",null,"1개",true));recipes.save(new Recipe("무조림",null,null,"EASY",20,2,"PUBLISHED"));mvc.perform(get("/api/v1/search").param("q","무")).andExpect(status().isOk()).andExpect(jsonPath("$.data.items.length()").value(2)).andExpect(jsonPath("$.data.ingredients.length()").value(1)).andExpect(jsonPath("$.data.recipes.length()").value(1)).andExpect(jsonPath("$.data.reels.length()").value(0)).andExpect(jsonPath("$.data.ingredientCount").value(1)).andExpect(jsonPath("$.data.recipeCount").value(1)).andExpect(jsonPath("$.data.reelCount").value(0));}
 @Test void rejectsBlankQuery() throws Exception{mvc.perform(get("/api/v1/search").param("q","")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("COMMON_VALIDATION_FAILED"));}
 @Test void returnsTrendingSearches() throws Exception{mvc.perform(get("/api/v1/search").param("q","무")).andExpect(status().isOk());mvc.perform(get("/api/v1/search/trending")).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].keyword").value("무")).andExpect(jsonPath("$.data[0].searchCount").value(1));}
 @Test void returnsAuthenticatedUsersRecentSearches() throws Exception{User user=users.save(new User("search@example.com","검색",null,"ACTIVE"));String token="Bearer "+jwt.createAccessToken(user.getId());mvc.perform(get("/api/v1/search").header("Authorization",token).param("q","무")).andExpect(status().isOk());mvc.perform(get("/api/v1/users/me/recent-searches").header("Authorization",token)).andExpect(status().isOk()).andExpect(jsonPath("$.data[0].keyword").value("무"));}
}
